### ISSUE TITLE
Upgrade gem or change maintainers

### ISSUE THREAD

**Issue by bradgessler** [joliss/markdown-rails#12]
There's a few out-of-date dependencies that are solved by:

* RDiscount version bump - https://github.com/v1nc3ntlaw/markdown-rails/commit/39fd6b59f0d43ade38d62aedb48535cb9fe89936
* Rails 6 compatibility - https://github.com/joliss/markdown-rails/pull/11

Please consider merging in these changes soon or if you're too busy, http://github.com/polleverywhere could take over maintaining and releasing this gem.

**Comment by mariuszmikolajczak** [comment]
Sadly rdiscount 1.6.8 doesn't compile on Big Sur Mac OS release, it would be cool to have RDiscount version bumped.

**Comment by joliss** [comment]
> Please consider merging in these changes soon or if you're too busy, http://github.com/polleverywhere could take over maintaining and releasing this gem.

I'd love for you to take over! Which RubyGems username(s) would you like me to add?

**Comment by bradgessler** [comment]
bradgessler

**Comment by joliss** [comment]
Done! I'll replace the README with a redirect note - at what location will you be hosting your copy/fork?

**Comment by bradgessler** [comment]
You can redirect to https://github.com/polleverywhere/markdown-rails or give me push access to your repo and I’ll make the update.

**Comment by bradgessler** [comment]
Oops, also, I gave you the wrong Rubygems username. Could you change to `brad` via `gem owner markdown-rails --add brad`

**Comment by joliss** [comment]
Thanks, done!
