### ISSUE TITLE
still recommended?

### ISSUE THREAD

**Issue by mathieujobin** [joliss/markdown-rails#9]
do you still recommend using this gem with recent rails 4.1 or 4.2 ?

you mention on your README a "different" solution on a stackoverflow link

should we update this gem with that solution. Erb support is nice.
but I'd prefer including a gem in my project instead of copy/pasting a file in my lib directory.

thanks

**Comment by joliss** [comment]
The StackOverflow solution is *probabably* better, but I honestly haven't kept up with Rails recently.

Either should be OK.

**Comment by bradgessler** [comment]
This is still a useful integration. Do you have plans to keep the dependencies up-to-date and keep up with the latest rails releases?

**Comment by joliss** [comment]
I won't be able to invest a whole lot of time into this gem, but if you send pull requests I'll do my best to merge them.

**Comment by joliss** [comment]
(I'm not using Rails 5 myself at the moment.)

**Comment by mathieujobin** [comment]
ah well, Rails 6 is around the corner
